# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        files: \.py$
      - id: end-of-file-fixer
        files: \.py$
      - id: check-yaml
        files: \.py$
      - id: check-added-large-files
        files: \.py$
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python
        exclude: ^db/|^custom_methods/path_helpers
  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        name: flake8
        args: [
          "--max-line-length=120",
          "--ignore=W503,E203"
        ]
        entry: flake8
        language: system
        types: [ python ]
        files: \.py$
        exclude: ^db/|^custom_methods/path_helpers|__init__.py$
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true